version: '3.9'

services:
  nextjs:
    image: skriva:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skriva
    ports:
      - 80:3000
    restart: unless-stopped

